[uwsgi]
module = app:app
master = true
processes = 4
threads = 2
http = ssdwm.com:8000
vacuum = true
buffer-size = 32768
enable-threads = true
single-interpreter = true
die-on-term = true
logto = uwsgi.log