[uwsgi]
module = app:app
master = true
processes = 4
threads = 2
http = 0.0.0.0:80
vacuum = true
buffer-size = 32768
enable-threads = true
single-interpreter = true
die-on-term = true
logto = uwsgi.log